### ISSUE TITLE
JSON formatting skipped

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/mlxprs#10]
I have a search that returns a few documents.

The first time I execute the search I get something like this:
![image](https://user-images.githubusercontent.com/1315891/59918870-f9df2e80-93f3-11e9-9cd1-5454b0a8eff0.png)

The next time I execute I get something like this:
![image](https://user-images.githubusercontent.com/1315891/59918898-0cf1fe80-93f4-11e9-94ab-f3a5552ebb71.png)

If I keep executing the search, the JSON formatting will toggle back and forth between formatted and not formatted.

With much larger results I have seen where spaces are injected inline and the JSON is partially corrupted. This one is harder to reproduce.

**Comment by mikrovvelle** [comment]
Have seen this as well and tried to catch the problem in debugging. It appears that the promise after `vscode.window.showTextDocument()` only fires about half of the time. I'll investigate and may need to follow up with VS Code team.

**Comment by mikrovvelle** [comment]
Posted a summary of the problem on the VS Code Slack a while ago, and I'm going to add it here before it gets lost (slightly touched up for context; no answers on Slack):

---
I think we've got a race condition in how VS Code does its formatting, especially for JSON.

To demo the problem, this is how mlxprs handles queries to MarkLogic, and then attempts to format the results:

1. Update the content for a URI in a `TextDocumentContentProvider` implementation (with ugly JSON all crammed on one line):
    - set a `Map<string, string>` value to the new (ugly) incoming JSON results
    - run `this._onDidChange.fire()` to let VS Code know the document content has changed
2. `.then()` Format the JSON contents using `executeCommand('vscode.executeFormatDocumentProvider', uri, options)`
3. `.then()` Show the document with `window.showTextDocument(doc)`

The problem is every other time I run this code in my extension, the JSON content doesn't get formatted. I show the ugly one-line JSON.

If I add a ~50ms wait between steps 1 and 2, then the JSON gets formatted about 90% of the time.
It's hard for me to figure out what `executeCommand` is actually doing under the hood to get the contents it's going to format, but it seems that if it runs too early, it gets a stale set of document contents at a given URI. In this case, that's the older, _already-formatted_ JSON from the previous query. So then it returns no edits.

Is there a way I can run the `executeFormatDocumentProvider` logic myself on a lower level, so only formatted JSON gets into my `TextDocumentContentProvider`, or be sure `executeCommand` isn't racing with `_onDidChange.fire()`?

**Comment by mikrovvelle** [comment]
Think I've got a reliable fix implemented:

https://github.com/mikrovvelle/mlxprs/releases/tag/v3.0.1-beta

I'll leave this up if anyone wants to test for a bit. In my own testing the issue appears fixed.
