### ISSUE TITLE
Support for ES2015 modules in debugger and inspector

### ISSUE THREAD

**Issue by zzzwan** [marklogic/mlxprs#28]
Our jsdebugger does not work fully with ES2015 modules (i.e. `import` syntax). 

  |     | `import` | `require()` |
  | -- | --------- | -----------|
  | Eval/launch | partial |   ✔︎ |
  | Attach | partial |   ✔︎ |

**Comment by jmakeig** [comment]
Reference to MarkLogic issue 53757.

**Comment by jmakeig** [comment]
@nupoork found that this actually works in MarkLogic 10.0-4, except for inspecting module-scoped variables that aren‘t used elsewhere. This is mostly a corner case with a simple, albeit not entirely obvious, workaround. This is a known issue in v8 and looks to be fixed in a more recent version. Node.js has the same issue. We need to document the workaround with a reference to the v8 bug in the README.

**Comment by jmakeig** [comment]
Fixed by #77
